/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Live */
        get: operations["list_live_vehicles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vehicle History */
        get: operations["vehicle_history_vehicles__vehicle_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stops Nearby */
        get: operations["stops_nearby_stops_nearby_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/{stop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stop By Id */
        get: operations["stop_by_id_stops__stop_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/{stop_id}/arrivals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stop Arrivals */
        get: operations["stop_arrivals_stops__stop_id__arrivals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/{stop_id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stop Predictions
         * @description Naive real-time ETAs from live vehicles (plan.md decision #7).
         *
         *     Empty when no live vehicle is currently approaching on a known shape —
         *     the client falls back to scheduled ``/arrivals``.
         */
        get: operations["stop_predictions_stops__stop_id__predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lines */
        get: operations["list_lines_lines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{short_name}/realtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Line Realtime */
        get: operations["line_realtime_lines__short_name__realtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{short_name}/shape": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Line Shape
         * @description GeoJSON FeatureCollection with one LineString per distinct shape on the line.
         */
        get: operations["line_shape_lines__short_name__shape_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{short_name}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Line Stats
         * @description Hourly activity buckets for a line from the continuous aggregate.
         */
        get: operations["line_stats_lines__short_name__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Trip */
        post: operations["plan_trip_trips_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Snapshot */
        get: operations["latest_snapshot_snapshots_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Snapshot */
        get: operations["download_snapshot_snapshots__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_alerts_rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_alerts_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_alerts_rules__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/catalog/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Catalog */
        post: operations["import_catalog_admin_catalog_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/snapshots/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Snapshot
         * @description Build the offline bundle now (the weekly cron is deferred).
         */
        post: operations["build_snapshot_admin_snapshots_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertRuleDTO */
        AlertRuleDTO: {
            /** Id */
            id: string;
            /** Device Id */
            device_id: string;
            /** Line Short Name */
            line_short_name: string;
            /** Stop Id */
            stop_id: string;
            /** Threshold Minutes */
            threshold_minutes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Triggered At */
            last_triggered_at: string | null;
        };
        /** ArrivalDTO */
        ArrivalDTO: {
            /** Arrival Seconds */
            arrival_seconds: number;
            /** Arrival Time */
            arrival_time: string;
            /** Trip Id */
            trip_id: string;
            /** Headsign */
            headsign: string | null;
            /** Route Id */
            route_id: string;
            /** Route Short Name */
            route_short_name: string;
            /** Route Long Name */
            route_long_name: string;
            /** Route Color */
            route_color: string | null;
        };
        /** ConnectionDTO */
        ConnectionDTO: {
            /** From Route */
            from_route: string | null;
            /** To Route */
            to_route: string | null;
            /** Wait Seconds */
            wait_seconds: number;
            /** Wait Minutes */
            wait_minutes: number;
            /** Kind */
            kind: string;
        };
        /** CoordinateDTO */
        CoordinateDTO: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** CreateAlertRuleRequest */
        CreateAlertRuleRequest: {
            /** Device Id */
            device_id: string;
            /** Line Short Name */
            line_short_name: string;
            /** Stop Id */
            stop_id: string;
            /** Threshold Minutes */
            threshold_minutes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HourlyLineStatDTO */
        HourlyLineStatDTO: {
            /**
             * Bucket
             * Format: date-time
             */
            bucket: string;
            /** Position Count */
            position_count: number;
            /** Vehicle Count */
            vehicle_count: number;
            /** Avg Speed Kmh */
            avg_speed_kmh: number;
            /** Max Speed Kmh */
            max_speed_kmh: number;
        };
        /** ImportResultDTO */
        ImportResultDTO: {
            /** Feed Version */
            feed_version: string;
            /** Agencies */
            agencies: number;
            /** Routes */
            routes: number;
            /** Stops */
            stops: number;
        };
        /** ItineraryDTO */
        ItineraryDTO: {
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** Duration S */
            duration_s: number;
            /** Walk Distance M */
            walk_distance_m: number;
            /** Transfers */
            transfers: number;
            /** Legs */
            legs: components["schemas"]["LegDTO"][];
            /** Connections */
            connections: components["schemas"]["ConnectionDTO"][];
        };
        /** LegDTO */
        LegDTO: {
            /** Mode */
            mode: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** Duration S */
            duration_s: number;
            /** Distance M */
            distance_m: number;
            /** From Name */
            from_name: string;
            /** From Lat */
            from_lat: number;
            /** From Lon */
            from_lon: number;
            /** To Name */
            to_name: string;
            /** To Lat */
            to_lat: number;
            /** To Lon */
            to_lon: number;
            /** Route Short Name */
            route_short_name: string | null;
            /** Route Long Name */
            route_long_name: string | null;
            /** Headsign */
            headsign: string | null;
            /** Interline */
            interline: boolean;
            /** Geometry */
            geometry: number[][];
        };
        /** LineRealtimeDTO */
        LineRealtimeDTO: {
            /** Routes */
            routes: components["schemas"]["RouteDTO"][];
            /** Vehicles */
            vehicles: components["schemas"]["VehiclePositionDTO"][];
        };
        /** PlanTripRequest */
        PlanTripRequest: {
            origin: components["schemas"]["CoordinateDTO"];
            destination: components["schemas"]["CoordinateDTO"];
            /** Depart At */
            depart_at?: string | null;
            /**
             * Max Itineraries
             * @default 3
             */
            max_itineraries: number;
        };
        /** PredictionDTO */
        PredictionDTO: {
            /** Line Short Name */
            line_short_name: string;
            /** Vehicle Id */
            vehicle_id: string;
            /** Distance M */
            distance_m: number;
            /** Speed Kmh */
            speed_kmh: number;
            /** Eta Seconds */
            eta_seconds: number;
            /** Eta Minutes */
            eta_minutes: number;
            /**
             * Eta At
             * Format: date-time
             */
            eta_at: string;
            /** Route Long Name */
            route_long_name: string | null;
            /** Route Color */
            route_color: string | null;
        };
        /** RouteDTO */
        RouteDTO: {
            /** Route Id */
            route_id: string;
            /** Agency Id */
            agency_id: string;
            /** Short Name */
            short_name: string;
            /** Long Name */
            long_name: string;
            /** Route Type */
            route_type: number;
            /** Color */
            color: string | null;
            /** Text Color */
            text_color: string | null;
        };
        /** SnapshotLatestDTO */
        SnapshotLatestDTO: {
            /** Version */
            version: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /** Route Count */
            route_count: number;
            /** Stop Count */
            stop_count: number;
            /** Url */
            url: string;
        };
        /** StopDTO */
        StopDTO: {
            /** Stop Id */
            stop_id: string;
            /** Code */
            code: string | null;
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Parent Station */
            parent_station: string | null;
            /** Wheelchair Boarding */
            wheelchair_boarding: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VehiclePositionDTO */
        VehiclePositionDTO: {
            /** Vehicle Id */
            vehicle_id: string;
            /** Line Id */
            line_id: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Speed Kmh */
            speed_kmh: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_live_vehicles_get: {
        parameters: {
            query?: {
                line_id?: string | null;
                fresh_seconds?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehiclePositionDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vehicle_history_vehicles__vehicle_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehiclePositionDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stops_nearby_stops_nearby_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                radius_m?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_by_id_stops__stop_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_arrivals_stops__stop_id__arrivals_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArrivalDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_predictions_stops__stop_id__predictions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lines_lines_get: {
        parameters: {
            query?: {
                agency_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    line_realtime_lines__short_name__realtime_get: {
        parameters: {
            query?: {
                fresh_seconds?: number;
            };
            header?: never;
            path: {
                short_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineRealtimeDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    line_shape_lines__short_name__shape_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                short_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    line_stats_lines__short_name__stats_get: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path: {
                short_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HourlyLineStatDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_trip_trips_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanTripRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_snapshot_snapshots_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotLatestDTO"];
                };
            };
        };
    };
    download_snapshot_snapshots__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_alerts_rules_get: {
        parameters: {
            query: {
                device_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_alerts_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAlertRuleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_alerts_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_catalog_admin_catalog_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResultDTO"];
                };
            };
        };
    };
    build_snapshot_admin_snapshots_build_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotLatestDTO"];
                };
            };
        };
    };
}
